#!/bin/bash
gcloud config set account elliot@percipientnetworks.com
gcloud config set project percipient-strongarm
gcloud config set compute/zone us-central1-a
gcloud config set container/cluster staging
gcloud config list
# one time gcloud alpha container get-credentials
# gcloud components update alpha
# gcloud components update kubectl
# gcloud alpha container get-credentials
kubectl config use-context gke_percipient-strongarm_us-central1-a_staging
